require_relative "analyze"
require_relative "commands/prep"
require_relative "commands/unprep"
require_relative "commands/add_partitions"
require_relative "commands/enable_sync"
require_relative "commands/fill"
require_relative "swap"
require_relative "unswap"
