#!/usr/bin/env ruby

require "thor"
require "pgslice/commands"

class PgSliceCommand < Thor
  def self.exit_on_failure?
    true
  end

  class_option :url, type: :string, desc: "A PostgreSQL connection string"

  desc "prep TABLE COLUMN PERIOD", "prepare the TABLE with specified column and period"
  def prep(table, column, period)
    PgSlice::Prep.new(table, column, period).run
  end

  desc "add_partitions TABLE", "add_partitions to TABLE, e.g. pgslice add_partitions visits --intermediate --past 1 --future 1"
  option :intermediate, type: :boolean
  option :past, type: :numeric, required: true
  option :future, type: :numeric, required: true
  def add_partitions(table, options)
    PgSlice::AddPartitions.new(table, options).run
  end

  desc "fill TABLE", "fill TABLE with original data"
  option :batch_by, type: :string, desc: "the column name of which will be used to batch data"
  option :source_table, type: :string
  option :dest_table, type: :string
  option :swapped, type: :boolean, desc: "source table and destination table have been swapped."
  option :batch_size, type: :numeric, required: true, default: 1000
  def fill(table)
    PgSlice::Fill.new(table, options).run
  end

  desc "unprep TABLE", "unprepare the TABLE"
  def unprep(table)
    PgSlice::Unprep.new(table, options).run
  end

  desc "analyze TABLE", "analyze the TABLE and print out information about partition tables"
  def analyze(table)
    PgSlice::Analyze.new(table, options).run
  end

  desc "swap TABLE", "swap the TABLE with the intermediate table"
  option :lock_timeout, type: :numeric, default: 30, desc: "timeout in seconds"
  def swap(table)
    PgSlice::Swap.new(table, options).run
  end

  desc "unswap TABLE", "unswap the TABLE with the intermediate table"
  def unswap(table)
    PgSlice::Unswap.new(table, options).run
  end
end

PgSliceCommand.start
